### ISSUE TITLE
Hi,thinks for your work,but ,how to install hdmap-msgs?

### ISSUE THREAD

**Issue by XuHao9166** [tanzby/Perception#1]

**Comment by tanzby** [comment]
The reason we need hdmap_msg is that a PolygonArray defined in hdmap_msg will do a mask work. If you don't have a HDMap, you can ignore it and remove relative code from package. Or you have, you need to modify some codes to receive your polygonarray, which is a set of vertexes describe ROI of roads actually.

**Comment by XuHao9166** [comment]
OK,Thank you very much.
